---
driver:
  name: vagrant
  require_chef_omnibus: latest
  customize:
    memory: 8192
    cpus: 8

provisioner:
  name: chef_solo


platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[python]
  - recipe[balanced-omnibus]
  attributes:
    citadel:
      access_key_id: <%= ENV['BALANCED_AWS_ACCESS_KEY_ID'] || ENV['AWS_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['BALANCED_AWS_SECRET_ACCESS_KEY'] || ENV['AWS_SECRET_ACCESS_KEY'] %>
