---
driver:
  name: vagrant
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[balanced-omnibus]
  attributes:
    citadel:
      access_key_id: <%= ENV['BALANCED_AWS_ACCESS_KEY_ID'] || ENV['AWS_ACCESS_KEY_ID'] %>
      secret_access_key: <%= ENV['BALANCED_AWS_SECRET_ACCESS_KEY'] || ENV['AWS_SECRET_ACCESS_KEY'] %>
